version: '3.8'

services:
  feyre:
    container_name: feyre
    env_file: 
      - config.env
    restart: always
    build: ./
    command: Feyre.py
    volumes:
      - ./_data:/home/app/_data

  # If you want to use redis
  # redis:
  #   container_name: redis
  #   build: ./redis